apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name }}
spec:
  replicas: {{ .Values.application.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.application.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name }}
    spec:
      containers:
      - name: {{ .Values.application.name }}
        image: "{{ .Values.application.image.repository }}:{{ .Values.application.image.tag }}"
        imagePullPolicy: {{ .Values.application.image.pullPolicy }}
        ports:
        {{- range .Values.application.ports }}
        - name: {{ .name }}
          containerPort: {{ .containerPort }}
          protocol: {{ .protocol }}
        {{- end }}
        resources:
          {{- toYaml .Values.application.resources | nindent 12 }}
